#Stereotaxy models 
STN: 'resources/STN.pkl'
cZI: 'resources/cZI.pkl' 
fct: 'resources/fct.pkl'
RN: 'resources/RN.pkl'
cZI_template: 'resources/cZI_template.fcsv'
STN_template: 'resources/STN_template.fcsv'
fct_template: 'resources/fct_template.fcsv'
RN_template: 'resources/RN_template.fcsv'
