#Stereotaxy models 
STN: 'resources/STN.pkl'
cZI: 'resources/cZI.pkl' 
template_fcsv: 'resources/target_template.fcsv'
cZI_template: 'resources/cZI_template.fcsv'
STN_template: 'resources/STN_template.fcsv'